### ISSUE TITLE
Quick start demo seems to not fail when database doesn't exist. 

### ISSUE THREAD

**Issue by rickylevan** [aodin/sol#2]
Somehow the log.Println at the bottom of the file was reached, although there should have been an error before.

**Comment by aodin** [comment]
`Open()` does not connect to the database. For more information see the relevant issue: https://github.com/lib/pq/issues/581

I've clarified this behavior with a call to `Ping()` in the quickstart: https://github.com/aodin/sol/commit/65ed6d38690433f48fab6b5c82c7883fbd8b2734
